<a href="https://colab.research.google.com/github/liz-robson/data-analysis-with-python/blob/main/NumPy_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Basics of Numpy

In [ ]:
import numpy as np

The Basics

In [ ]:
a = np.array([1,2,3], dtype='int16')

In [ ]:
print(a)

[1 2 3]


In [ ]:
b = np.array([[9.0, 8.0, 7.0], [6.0, 5.0, 4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [ ]:
#Get Dimension
a.ndim

1

In [ ]:
#Get Shape
b.shape

(2, 3)

In [ ]:
#Get Type
a.dtype

dtype('int16')

In [ ]:
#Get Size
a.itemsize
b.itemsize

8

Accessing/Changing specific elements, rows, columns etc.

In [ ]:
a = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])
print(a)


[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [ ]:
#Get a specifc element [r,c]
a[1, -2]

13

In [ ]:
#Get a specific row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [ ]:
#Get a specific column
a[:,2]

array([ 3, 10])

In [ ]:
#Getting a little more fancy [startindex:endindex:stepsize]
a[0,1:6:2]


array([2, 4, 6])

In [ ]:
# Change elements
a[1,5] = 20
print(a)


[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [ ]:
a[:,2] = [1,2]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


Initialising Different Arrays
**bold text**

In [ ]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

In [ ]:
np.full((2,2), 99)

array([[99, 99],
       [99, 99]])

In [ ]:
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [ ]:
#Initalise an array of decimal numbers
np.random.rand(4,2,3)

array([[[0.20095627, 0.19873004, 0.39745694],
        [0.47556103, 0.68075626, 0.43734576]],

       [[0.63938439, 0.16192519, 0.54394163],
        [0.69653681, 0.64344785, 0.39706037]],

       [[0.74851785, 0.12467845, 0.666405  ],
        [0.61793559, 0.97219105, 0.59595358]],

       [[0.50934389, 0.93505727, 0.99101339],
        [0.20955952, 0.97084768, 0.54131607]]])

In [ ]:
np.random.random_sample(a.shape)

array([[0.88400483, 0.05349364, 0.98813248, 0.24335235, 0.80019096,
        0.12975418, 0.34222597],
       [0.7586598 , 0.65895426, 0.5491508 , 0.72111088, 0.84990009,
        0.79930185, 0.24924339]])

In [ ]:
#Random integer values
np.random.randint(4,7, size=(3,3))

array([[5, 4, 4],
       [5, 4, 4],
       [5, 6, 4]])

In [ ]:
#Identity matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
#Repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


**Initialise Array Problem**

In [ ]:
output = np.ones((5,5))
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
z = np.zeros((3,3))
z[1,1] = 9
print(z)

[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]


In [ ]:
output[1:4,1:4] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


**Copying Arrays Warning**

In [ ]:
###### Be careful when copying arrays!!!

In [ ]:
a = np.array([1,2,3])
b = a
print(b)

[1 2 3]


In [ ]:
b[0] = 100
print(b)

[100   2   3]


In [ ]:
print(a)

[100   2   3]


In [ ]:
a = np.array([1,2,3])
b = a.copy()
print(b)

[1 2 3]


In [ ]:
b[0] = 100
print(b)

[100   2   3]


In [ ]:
print(a,b)

[1 2 3] [100   2   3]


**Mathematics**

In [ ]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [ ]:
a + 2

array([5, 6, 7, 8])

In [ ]:
a - 2

array([1, 2, 3, 4])

In [ ]:
a * 2

array([ 6,  8, 10, 12])

In [ ]:
a / 2

array([1.5, 2. , 2.5, 3. ])

In [ ]:
b = np.array([1,0,1,0])
print(b)

[1 0 1 0]


In [ ]:
a + b

array([4, 4, 6, 6])

In [ ]:
a ** 2

array([ 9, 16, 25, 36])

In [ ]:
# Take the sin
np.cos(a)

array([-0.9899925 , -0.65364362,  0.28366219,  0.96017029])

In [ ]:
##### Linear Algebra

In [ ]:
a = np.ones((2,3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
b = np.full((3,2),2)
print(b)

[[2 2]
 [2 2]
 [2 2]]


In [ ]:
np.matmul(a,b)

array([[6., 6.],
       [6., 6.]])

In [ ]:
c = np.identity(3)
np.linalg.det(c)

1.0

In [ ]:
##### Statistics

In [ ]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.min(stats, axis=0)

array([1, 2, 3])

In [ ]:
np.min(stats)

1

In [ ]:
np.max(stats, axis=1)

array([3, 6])

In [ ]:
np.sum(stats, axis=0)

array([5, 7, 9])

**Reorganising Arrays**

In [ ]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
print(before.shape)

(2, 4)


In [ ]:
after = before.reshape((8,1))
print(after)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [ ]:
after = before.reshape((2,2,2))
print(after)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
# Vertically stacking vectors

In [ ]:
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

In [ ]:
np.vstack([v1,v2,v2,v1])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8],
       [1, 2, 3, 4]])

In [ ]:
# Horizontal stack
np.hstack([v1,v2,v1])

array([1, 2, 3, 4, 5, 6, 7, 8, 1, 2, 3, 4])

**Loading Data and Advanced Indexing**

In [ ]:
filedata = np.genfromtxt('data.txt', delimiter=',')

In [ ]:
filedata.astype('int32')

In [ ]:
filedata = filedata.astype('int32')

**Boolean Masking and Advanced Indexing**




In [ ]:
filedata > 50

In [ ]:
filedata[filedata > 50]

In [ ]:
## You can index with a list in NumPy

In [ ]:
a = np.array([1,2,3,4,5,6,7,8,9])
print(a)

[1 2 3 4 5 6 7 8 9]


In [ ]:
a[[1,2,8]]

array([2, 3, 9])

In [ ]:
np.any(a < 50, axis=0)

True

In [ ]:
np.any(a < 50)

True

In [ ]:
np.all((a< 50) & (a > 0))

True